OS-18: users page
esipenko/okr pull request #11
Opened 2020-12-14 18:08 UTC by esipenko

2020-12-16 10:13 UTC, amalyuhin requested changes

2020-12-16 10:13 UTC, amalyuhin commented on packages/ui/src/components/users/UsersDesktop.vue
> +                <v-toolbar-title>Users</v-toolbar-title>
Заголовок страницы отличается для мобильного экрана и десктопа. И оба они отличаются от заголовков для других страниц). Это не очень хорошо, так как обычно такие вещи должны иметь одни стили. Я бы лучше сделал таким образом:
- заголовок отображал в компоненте-контейнере Users
- для списка добавил новый "глупый" компонент UsersList
- в компоненте Users отображал заголовок и UsersList с передачей в него признака isMobile в виде атрибута
- компоненты UsersDesktop и UsersMobile переименовал в UsersListDesktop и UsersListMobile, в UsersList в зависимости от признака isMobile отображал один из них

При таком подходе более четко происходит разграничение ответственностей.

2020-12-16 10:13 UTC, amalyuhin commented on packages/ui/src/components/users/UsersWrapper.vue
> +        window.addEventListener("resize", this.onResize);
Очень хорошо, что добавил реакцию на изменение размера окна. Но есть нюанс - при дальнейшем разделении различных страница на разные отображения для десктопа и мобилки этот код будет дублироваться. Можно вынести этот функционал в миксин. Но так как используется стор, то на мой взгляд более правильным решением будет сделать компонент обертку, который будет вычислять размер экрана, реагировать на ресайз и записывать значение isMobile в стор. В таком случае компоненты-контейнеры, в случае необходимости, могут брать это значение из стора и передавать его в свои дочерние компоненты в виде атрибута

2020-12-21 18:14 UTC, amalyuhin requested changes

2020-12-21 18:14 UTC, amalyuhin commented on packages/api/src/user/user.controller.ts
> +    @RoleControl(ACLRule.USERS_LIST)
По логике тут должно требоваться право ACLRule.USERS_EDIT. А в методе удаления ACLRule.USERS_DELETE

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/App.vue
>          { rules: [], title: "Users", to: "/users" },
Для пользователей тоже можно ограничить доступ по праву ACLRule.USERS_LIST

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/components/users/UserForm.vue
> +                    <v-btn color="primary" text @click="close"> cancel </v-btn>
Основная кнопка тут "edit", думаю для "cancel" должен быть класс secondary

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/components/users/UserForm.vue
> +                        ></v-text-field>
Поле для изменения роли тоже нужно перенести в эту форму. Только для администратора нужно запрещать ее редактировать. А в списке отображать роль текстом.

2020-12-21 18:14 UTC, amalyuhin commented on packages/shared/src/acl.rules.ts
> +}
По-хорошему, при изменении кода в пакете "shared", нужно обновлять его версию в packages/shared/package.json. В противном случае, если этот пакет уже был установлен, то `yarn install` не установит новую версию.

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/App.vue
> +    components: { HelloWorld },
Компонент HelloWorld нужно конечно переименовать, совсем непонятно за что он отвечает

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/components/Login.vue
> +            .then(() => this["$router"].push("/"))
А почему меняешь `this.$router` на `this["$router"]`? Это линтер так настроен?

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/components/ProjectsForm.vue
> +                    <OpenFormButton
Логически выглядит так, что кнопка открытия диалога с формой должна находится в компоненте Projects. Иначе получается, что кнопка открытия формы находится в компоненте самой формы - немного запутанно.

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/components/OpenFormButton.vue
> +<template>
Не уверен в необходимости этого компонента - никакой функциональной нагрузки он не несет, а только добавляет стили отображения. Кажется, что либо эти стили нужно вынести в компонент Projects, либо сам компонент сделать более универсальным, чтобы его можно было переиспользовать.

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/components/users/UsersMobile.vue
> +                                    <user-roles :item="item" />
Здесь достаточно выводить текстом роль пользователя, а `user-roles` видимо нужно вынести в UserForm

2020-12-21 18:14 UTC, amalyuhin commented on packages/ui/src/components/users/UsersMobile.vue
> +        return rules.filter((r) => actionRules.includes(r)).length !== 0;
Для подобного рода проверок лучше использовать методы Array.some() и Array.every():
`return rules.some((rule) => actionRules.includes(rule));`

2020-12-22 03:54 UTC, esipenko commented on packages/ui/src/components/Login.vue
> +            .then(() => this["$router"].push("/"))
Да, я пытался как-то другими способами избавиться от ругани линтера, но пока не получилось

2020-12-22 03:56 UTC, esipenko commented on packages/ui/src/components/ProjectsForm.vue
> +                    <OpenFormButton
Это делалось по примеру кода из доки vuetify, но можно исправить

2020-12-22 03:57 UTC, esipenko commented on packages/ui/src/components/OpenFormButton.vue
> +<template>
У меня была одинаковая кнопка в двух местах, поэтому я вынес её отдельно
ЛУчшим решением было бы конечно сделать просто общий компонент с модалкой, куда в слот я бы клал контент

2020-12-22 16:00 UTC, esipenko commented on packages/ui/src/App.vue
>          { rules: [], title: "Users", to: "/users" },
Ой, это я пропустил, сейчас так и есть. Правила задаются в meta в роутере

2021-01-19 10:48 UTC, merged